"""Curated corpus: English Wikipedia articles on AI / machine learning.

Titles are resolved through Wikipedia's redirect handling, so common aliases are safe.
The list is committed so ingestion is fully reproducible.
"""

ARTICLES: list[str] = [
    # --- Foundations of AI & ML ---
    "Artificial intelligence",
    "Machine learning",
    "Deep learning",
    "Supervised learning",
    "Unsupervised learning",
    "Semi-supervised learning",
    "Self-supervised learning",
    "Reinforcement learning",
    "Online machine learning",
    "Active learning (machine learning)",
    "Transfer learning",
    "Multi-task learning",
    "Meta-learning (computer science)",
    "Federated learning",
    "Curriculum learning",
    "Ensemble learning",
    "Statistical learning theory",
    "Computational learning theory",
    "Probably approximately correct learning",
    "Vapnik–Chervonenkis dimension",
    "Bias–variance tradeoff",
    "Overfitting",
    "Regularization (mathematics)",
    "Cross-validation (statistics)",
    "Hyperparameter optimization",
    "Feature engineering",
    "Feature selection",
    "Feature learning",
    "Dimensionality reduction",
    "Curse of dimensionality",
    "No free lunch theorem",
    "Occam's razor",
    # --- Classic ML algorithms ---
    "Linear regression",
    "Logistic regression",
    "Support vector machine",
    "Decision tree learning",
    "Random forest",
    "Gradient boosting",
    "XGBoost",
    "K-nearest neighbors algorithm",
    "Naive Bayes classifier",
    "K-means clustering",
    "Hierarchical clustering",
    "DBSCAN",
    "Principal component analysis",
    "Independent component analysis",
    "Linear discriminant analysis",
    "Singular value decomposition",
    "T-distributed stochastic neighbor embedding",
    "UMAP",
    "Hidden Markov model",
    "Markov chain",
    "Markov decision process",
    "Expectation–maximization algorithm",
    "Gaussian process",
    "Bayesian network",
    "Bayesian inference",
    "Maximum likelihood estimation",
    "Maximum a posteriori estimation",
    "Kernel method",
    "Perceptron",
    "Multilayer perceptron",
    "Anomaly detection",
    "Collaborative filtering",
    "Recommender system",
    "Learning to rank",
    "Association rule learning",
    # --- Neural networks & deep learning ---
    "Artificial neural network",
    "Backpropagation",
    "Activation function",
    "Rectifier (neural networks)",
    "Sigmoid function",
    "Softmax function",
    "Convolutional neural network",
    "Recurrent neural network",
    "Long short-term memory",
    "Gated recurrent unit",
    "Autoencoder",
    "Variational autoencoder",
    "Generative adversarial network",
    "Diffusion model",
    "Transformer (deep learning architecture)",
    "Attention (machine learning)",
    "Residual neural network",
    "Batch normalization",
    "Dropout (neural networks)",
    "Vanishing gradient problem",
    "Weight initialization",
    "Graph neural network",
    "Capsule neural network",
    "Spiking neural network",
    "Neural radiance field",
    "Word embedding",
    "Word2vec",
    "GloVe",
    "Sentence embedding",
    "Knowledge distillation",
    "Neural architecture search",
    "Universal approximation theorem",
    "Deep belief network",
    "Boltzmann machine",
    "Restricted Boltzmann machine",
    "Hopfield network",
    "Self-organizing map",
    "Echo state network",
    "Siamese neural network",
    "U-Net",
    "AlexNet",
    "VGGNet",
    "Inception (deep learning architecture)",
    "EfficientNet",
    "Vision transformer",
    # --- Optimization & training ---
    "Gradient descent",
    "Stochastic gradient descent",
    "Adam (optimization algorithm)",
    "Learning rate",
    "Loss function",
    "Cross-entropy",
    "Mean squared error",
    "Huber loss",
    "Early stopping",
    "Data augmentation",
    "Convex optimization",
    "Simulated annealing",
    "Genetic algorithm",
    "Evolutionary algorithm",
    "Particle swarm optimization",
    "Bayesian optimization",
    "Automatic differentiation",
    "Newton's method in optimization",
    "Conjugate gradient method",
    "Coordinate descent",
    # --- NLP & language models ---
    "Natural language processing",
    "Large language model",
    "Language model",
    "Generative pre-trained transformer",
    "GPT-2",
    "GPT-3",
    "GPT-4",
    "ChatGPT",
    "BERT (language model)",
    "T5 (language model)",
    "LLaMA",
    "Claude (language model)",
    "Gemini (language model)",
    "Mistral AI",
    "Foundation model",
    "Prompt engineering",
    "Few-shot learning",
    "Zero-shot learning",
    "In-context learning",
    "Chain-of-thought prompting",
    "Retrieval-augmented generation",
    "Hallucination (artificial intelligence)",
    "Fine-tuning (deep learning)",
    "Reinforcement learning from human feedback",
    "Direct preference optimization",
    "Instruction tuning",
    "Byte-pair encoding",
    "Tokenization (lexical analysis)",
    "N-gram",
    "Tf–idf",
    "Okapi BM25",
    "Latent Dirichlet allocation",
    "Topic model",
    "Named-entity recognition",
    "Part-of-speech tagging",
    "Sentiment analysis",
    "Machine translation",
    "Neural machine translation",
    "Question answering",
    "Text summarization",
    "Information retrieval",
    "Information extraction",
    "Semantic search",
    "Vector database",
    "Nearest neighbor search",
    "Hierarchical navigable small world",
    "Locality-sensitive hashing",
    "Cosine similarity",
    "Seq2seq",
    "Beam search",
    "Perplexity",
    "BLEU",
    "ROUGE (metric)",
    "Speech recognition",
    "Speech synthesis",
    "Whisper (speech recognition system)",
    # --- Computer vision ---
    "Computer vision",
    "Image segmentation",
    "Object detection",
    "Facial recognition system",
    "Optical character recognition",
    "Image registration",
    "Feature (computer vision)",
    "Scale-invariant feature transform",
    "Optical flow",
    "Image classification",
    "Semantic segmentation",
    "Pose estimation",
    "Stable Diffusion",
    "DALL-E",
    "Midjourney",
    "Text-to-image model",
    "Text-to-video model",
    "Generative artificial intelligence",
    "Deepfake",
    "Super-resolution imaging",
    # --- Reinforcement learning ---
    "Q-learning",
    "Temporal difference learning",
    "Policy gradient method",
    "Proximal policy optimization",
    "Actor-critic algorithm",
    "Multi-armed bandit",
    "Monte Carlo tree search",
    "AlphaGo",
    "AlphaZero",
    "AlphaFold",
    "MuZero",
    "Deep reinforcement learning",
    "Reward model",
    "Exploration–exploitation dilemma",
    "Bellman equation",
    "Dynamic programming",
    # --- Evaluation, statistics & data ---
    "Accuracy and precision",
    "Precision and recall",
    "F-score",
    "Receiver operating characteristic",
    "Confusion matrix",
    "Statistical hypothesis test",
    "P-value",
    "Bayes' theorem",
    "Central limit theorem",
    "Normal distribution",
    "Entropy (information theory)",
    "Kullback–Leibler divergence",
    "Mutual information",
    "Information theory",
    "Monte Carlo method",
    "Markov chain Monte Carlo",
    "Bootstrapping (statistics)",
    "A/B testing",
    "Data mining",
    "Big data",
    "Data science",
    "Exploratory data analysis",
    "Missing data",
    "Oversampling and undersampling in data analysis",
    "Synthetic data",
    "Data set",
    "ImageNet",
    "MNIST database",
    # --- Systems, hardware & MLOps ---
    "MLOps",
    "Graphics processing unit",
    "Tensor Processing Unit",
    "CUDA",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "Pandas (software)",
    "NumPy",
    "Apache Spark",
    "Kubernetes",
    "Docker (software)",
    "Model compression",
    "Quantization (signal processing)",
    "Edge computing",
    "Distributed computing",
    "MapReduce",
    "Parallel computing",
    "High-performance computing",
    # --- AI safety, ethics & society ---
    "AI safety",
    "AI alignment",
    "Existential risk from artificial intelligence",
    "Ethics of artificial intelligence",
    "Algorithmic bias",
    "Explainable artificial intelligence",
    "Fairness (machine learning)",
    "Adversarial machine learning",
    "Prompt injection",
    "Artificial general intelligence",
    "Superintelligence",
    "Technological singularity",
    "AI takeover",
    "Regulation of artificial intelligence",
    "Artificial Intelligence Act",
    "AI winter",
    "History of artificial intelligence",
    "Turing test",
    "Chinese room",
    "Symbolic artificial intelligence",
    "Expert system",
    "Knowledge representation and reasoning",
    "Automated planning and scheduling",
    "Computational creativity",
    "Affective computing",
    "Robotics",
    "Autonomous robot",
    "Self-driving car",
    # --- People & organizations ---
    "Alan Turing",
    "John McCarthy (computer scientist)",
    "Marvin Minsky",
    "Geoffrey Hinton",
    "Yann LeCun",
    "Yoshua Bengio",
    "Andrew Ng",
    "Demis Hassabis",
    "Ilya Sutskever",
    "Fei-Fei Li",
    "Ian Goodfellow",
    "Jürgen Schmidhuber",
    "Claude Shannon",
    "Norbert Wiener",
    "OpenAI",
    "DeepMind",
    "Anthropic",
    "Hugging Face",
    "Sam Altman",
    "Dario Amodei",
]
